### ISSUE TITLE
[Docs]: Automated documentation

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cnpg-i#22]
### Is there an existing issue already for your request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new documentation enhancement to be evaluated.

### What problem in the existing documentation this issue aims to solve?

We need an automated way to generate the documentation of the API.

### Describe what additions need to be done to the documentation

Use https://github.com/pseudomuto/protoc-gen-doc

### Backport?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fcanovai** [comment]
Done in https://github.com/cloudnative-pg/cnpg-i/pull/31
