### ISSUE TITLE
[Feature]: Pipeline MVP

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cnpg-i#29]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

CNPG-I should have a pipeline to validate the source, build documentation, linting, check build is coherent with the protocol, spellcheck ...

### Describe the solution you'd like

Create a GitHub action to fulfil the above. Feel free to extend the scope during investigation.

### Describe alternatives you've considered

N/A

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fcanovai** [comment]
Done in https://github.com/cloudnative-pg/cnpg-i/pull/31
