### ISSUE TITLE
[Bug]: Reconciler callback gets two copies of Cluster resource, no Kind

### ISSUE THREAD

**Issue by ringerc** [cloudnative-pg/cnpg-i#59]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### What happened?

Implementations of the CNPG-I reconciler hook get two copies of the cluster resource in the `reconciler.ReconcilerHooksRequest`. The same `Cluster` manifest seems to be in both `request.ResourceDefinition` and `request.ClusterDefinition`.

It doesn't seem to expose other resources as they are inspected by CNPG-I like the `Pod`s etc as the reconciler sweeps them.

There's no helper to get the kind of operation or target resource like there is on some of the other plugin callbacks either.

These are available via lifecycle callbacks, but only when CNPG is actually changing them.

Sample reconcile hook implementation attached:
[reconcile.go.txt](https://github.com/user-attachments/files/16077365/reconcile.go.txt)

This can be added into the CNPG-I hello-world plugin with something like this added to the capabilities reporting

```
                        // internal/reconcile
                        {
                                Type: &identity.PluginCapability_Service_{
                                        Service: &identity.PluginCapability_Service{
                                                Type: identity.PluginCapability_Service_TYPE_RECONCILER_HOOKS,
                                        },
                                },
                        },
```

and this to `cmd/plugin`'s handlers list:

```
                reconciler.RegisterReconcilerHooksServer(server, reconcileImpl.ReconcileHandler{})
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ringerc** [comment]
This might not actually be a bug, maybe it's working as intended. But it's a bit hard to understand what its purpose is if so.

**Comment by armru** [comment]
Hello, Craig. This is working as intended, given that every custom reconciliation always receives the `Cluster` object; in the case of the cluster, it will receive two times the object. While unclear, this saves a lot of boilerplate because we end up using a single interface.

As an action on this issue, I think we should document this behavior.
