### ISSUE TITLE
[Bug]: OperatorCapability TYPE_MUTATE_POD unimplemented and ignored

### ISSUE THREAD

**Issue by ringerc** [cloudnative-pg/cnpg-i#65]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### What happened?

The `TYPE_MUTATE_POD` action for `OperatorCapability` is unused, unimplemented and ignored.

A warning or error should be emitted if it is used, or it should be removed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ringerc** [comment]
Explanation given was

>  Mutate pod afaik is deprecated, it was used before lifecycle existed

**Comment by armru** [comment]
we should proceed to remove it
